-- ============================================================================
-- EBTL — Supabase schema backup: constraints
-- Primary keys / uniques first, then checks, then foreign keys.
-- Assumes an empty target database (see scripts/restore.sh).
-- ============================================================================

SET search_path = public, extensions;

-- ---------------------------------------------------------------------------
-- Primary keys and unique constraints
-- ---------------------------------------------------------------------------

ALTER TABLE public.app_events ADD CONSTRAINT app_events_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_daily_closings ADD CONSTRAINT cart_daily_closings_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_daily_closings ADD CONSTRAINT cart_daily_closings_location_id_business_date_key UNIQUE (location_id, business_date);
ALTER TABLE public.cart_daily_openings ADD CONSTRAINT cart_daily_openings_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_daily_openings ADD CONSTRAINT cart_daily_openings_location_id_business_date_key UNIQUE (location_id, business_date);
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_unique UNIQUE (cart_item_id, addon_variant_id);
ALTER TABLE public.cart_item_removed_ingredients ADD CONSTRAINT cart_item_removed_ingredients_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_item_removed_ingredients ADD CONSTRAINT cart_item_removed_ingredients_unique UNIQUE (cart_item_id, recipe_item_id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_variant_customization_key UNIQUE (cart_id, variant_id, customization_hash);
ALTER TABLE public.carts ADD CONSTRAINT carts_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_addresses ADD CONSTRAINT customer_addresses_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_credit_ledger ADD CONSTRAINT customer_credit_ledger_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_favorite_products ADD CONSTRAINT customer_favorite_products_pkey PRIMARY KEY (customer_id, product_id);
ALTER TABLE public.customer_notifications ADD CONSTRAINT customer_notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_notifications ADD CONSTRAINT customer_notifications_dedupe_key_key UNIQUE (dedupe_key);
ALTER TABLE public.customer_payment_methods ADD CONSTRAINT customer_payment_methods_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_payment_methods ADD CONSTRAINT customer_payment_methods_provider_token_unique UNIQUE (provider, provider_token_id);
ALTER TABLE public.customer_push_tokens ADD CONSTRAINT customer_push_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_push_tokens ADD CONSTRAINT customer_push_tokens_unique_per_customer UNIQUE (customer_id, token_hash);
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE public.customers ADD CONSTRAINT customers_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE public.customers ADD CONSTRAINT customers_email_key UNIQUE (email);
ALTER TABLE public.customers ADD CONSTRAINT customers_phone_key UNIQUE (phone);
ALTER TABLE public.employee_credentials ADD CONSTRAINT employee_credentials_pkey PRIMARY KEY (id);
ALTER TABLE public.employee_credentials ADD CONSTRAINT employee_credentials_employee_id_key UNIQUE (employee_id);
ALTER TABLE public.employee_credentials ADD CONSTRAINT employee_credentials_username_key UNIQUE (username);
ALTER TABLE public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE public.employees ADD CONSTRAINT employees_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_pkey PRIMARY KEY (id);
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_name_key UNIQUE (name);
ALTER TABLE public.inventory_balances ADD CONSTRAINT inventory_balances_pkey PRIMARY KEY (ingredient_id, location_id);
ALTER TABLE public.liquor_types ADD CONSTRAINT liquor_types_pkey PRIMARY KEY (id);
ALTER TABLE public.liquor_types ADD CONSTRAINT liquor_types_name_key UNIQUE (name);
ALTER TABLE public.location_opening_hours ADD CONSTRAINT location_opening_hours_pkey PRIMARY KEY (id);
ALTER TABLE public.location_opening_hours ADD CONSTRAINT location_opening_hours_unique_day UNIQUE (location_id, day_of_week);
ALTER TABLE public.locations ADD CONSTRAINT locations_pkey PRIMARY KEY (id);
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT loyalty_accounts_pkey PRIMARY KEY (customer_id);
ALTER TABLE public.loyalty_transactions ADD CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.order_inventory_consumptions ADD CONSTRAINT order_inventory_consumptions_pkey PRIMARY KEY (order_id);
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_pkey PRIMARY KEY (id);
ALTER TABLE public.order_item_inventory_components ADD CONSTRAINT order_item_inventory_components_pkey PRIMARY KEY (id);
ALTER TABLE public.order_item_removed_ingredients ADD CONSTRAINT order_item_removed_ingredients_pkey PRIMARY KEY (id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.order_number_counters ADD CONSTRAINT order_number_counters_pkey PRIMARY KEY (order_date);
ALTER TABLE public.order_prep_tasks ADD CONSTRAINT order_prep_tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE public.orders ADD CONSTRAINT orders_business_date_order_number_key UNIQUE (business_date, order_number);
ALTER TABLE public.payment_events ADD CONSTRAINT payment_events_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_events ADD CONSTRAINT payment_events_provider_event_id_key UNIQUE (provider_event_id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_idempotency_key_key UNIQUE (idempotency_key);
ALTER TABLE public.prep_stations ADD CONSTRAINT prep_stations_pkey PRIMARY KEY (id);
ALTER TABLE public.prep_stations ADD CONSTRAINT prep_stations_location_id_name_key UNIQUE (location_id, name);
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_name_key UNIQUE (name);
ALTER TABLE public.product_liquor_compatibility ADD CONSTRAINT product_liquor_compatibility_pkey PRIMARY KEY (product_id, liquor_type_id);
ALTER TABLE public.product_tags ADD CONSTRAINT product_tags_pkey PRIMARY KEY (id);
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_slug_key UNIQUE (slug);
ALTER TABLE public.promotion_redemptions ADD CONSTRAINT promotion_redemptions_pkey PRIMARY KEY (id);
ALTER TABLE public.promotions ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);
ALTER TABLE public.promotions ADD CONSTRAINT promotions_code_key UNIQUE (code);
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_purchase_order_id_ingredient_id_key UNIQUE (purchase_order_id, ingredient_id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_items ADD CONSTRAINT recipe_items_pkey PRIMARY KEY (id);
ALTER TABLE public.recipes ADD CONSTRAINT recipes_pkey PRIMARY KEY (id);
ALTER TABLE public.recipes ADD CONSTRAINT recipes_product_id_version_key UNIQUE (product_id, version);
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.referrals ADD CONSTRAINT referrals_pkey PRIMARY KEY (id);
ALTER TABLE public.referrals ADD CONSTRAINT referrals_referee_customer_id_key UNIQUE (referee_customer_id);
ALTER TABLE public.shop_settings ADD CONSTRAINT shop_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_transfer_id_ingredient_id_key UNIQUE (transfer_id, ingredient_id);
ALTER TABLE public.stock_transfer_movement_events ADD CONSTRAINT stock_transfer_movement_events_pkey PRIMARY KEY (transfer_id, event_type);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_transfer_number_key UNIQUE (transfer_number);
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_name_key UNIQUE (name);

-- ---------------------------------------------------------------------------
-- Check constraints
-- ---------------------------------------------------------------------------

ALTER TABLE public.cart_daily_closings ADD CONSTRAINT non_negative_closing_cash CHECK ((closing_cash >= (0)::numeric));
ALTER TABLE public.cart_daily_closings ADD CONSTRAINT non_negative_waste_value CHECK ((total_waste_value >= (0)::numeric));
ALTER TABLE public.cart_daily_openings ADD CONSTRAINT non_negative_opening_cash CHECK ((opening_cash >= (0)::numeric));
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_price_non_negative CHECK ((unit_price_inc_vat_snapshot >= (0)::numeric));
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_qty_positive CHECK ((quantity_per_parent > 0));
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_serving_count_positive CHECK ((serving_count_snapshot > 0));
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_vat_valid CHECK (((vat_rate_snapshot >= (0)::numeric) AND (vat_rate_snapshot <= (1)::numeric)));
ALTER TABLE public.cart_item_removed_ingredients ADD CONSTRAINT cart_item_removed_ingredients_quantity_non_negative CHECK ((quantity_snapshot >= (0)::numeric));
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_base_price_non_negative CHECK (((base_unit_price_inc_vat_snapshot IS NULL) OR (base_unit_price_inc_vat_snapshot >= (0)::numeric)));
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_customization_total_non_negative CHECK ((customization_total_inc_vat_snapshot >= (0)::numeric));
ALTER TABLE public.cart_items ADD CONSTRAINT non_negative_cart_price CHECK ((unit_price_inc_vat_snapshot >= (0)::numeric));
ALTER TABLE public.cart_items ADD CONSTRAINT positive_cart_quantity CHECK ((quantity > 0));
ALTER TABLE public.cart_items ADD CONSTRAINT valid_cart_vat_rate_snapshot CHECK (((vat_rate_snapshot >= (0)::numeric) AND (vat_rate_snapshot <= (1)::numeric)));
ALTER TABLE public.carts ADD CONSTRAINT valid_cart_status CHECK ((status = ANY (ARRAY['active'::text, 'converted'::text, 'abandoned'::text])));
ALTER TABLE public.customer_credit_ledger ADD CONSTRAINT customer_credit_ledger_entry_shape_chk CHECK ((((reason = 'referral_reward'::text) AND (delta_amount > (0)::numeric) AND (referral_id IS NOT NULL)) OR ((reason = 'order_redemption'::text) AND (delta_amount < (0)::numeric) AND (order_id IS NOT NULL)) OR ((reason = 'admin_adjustment'::text) AND (delta_amount <> (0)::numeric))));
ALTER TABLE public.customer_credit_ledger ADD CONSTRAINT customer_credit_ledger_reason_chk CHECK ((reason = ANY (ARRAY['referral_reward'::text, 'order_redemption'::text, 'admin_adjustment'::text])));
ALTER TABLE public.customer_payment_methods ADD CONSTRAINT customer_payment_methods_expiry_month_valid CHECK (((expiry_month IS NULL) OR ((expiry_month >= 1) AND (expiry_month <= 12))));
ALTER TABLE public.customers ADD CONSTRAINT customers_gender_valid CHECK (((gender IS NULL) OR (gender = ANY (ARRAY['male'::text, 'female'::text]))));
ALTER TABLE public.employee_credentials ADD CONSTRAINT employee_credentials_username_format CHECK ((username ~ '^[a-zA-Z0-9._-]{3,}$'::text));
ALTER TABLE public.employees ADD CONSTRAINT employees_prep_location_required CHECK (((role <> 'prep'::public.employee_role) OR (default_location_id IS NOT NULL)));
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_icon_key_format CHECK (((icon_key IS NULL) OR (icon_key ~ '^[a-z0-9]+([_-][a-z0-9]+)*$'::text)));
ALTER TABLE public.ingredients ADD CONSTRAINT non_negative_purchase_cost CHECK (((purchase_unit_cost IS NULL) OR (purchase_unit_cost >= (0)::numeric)));
ALTER TABLE public.ingredients ADD CONSTRAINT non_negative_shelf_life CHECK (((shelf_life_days IS NULL) OR (shelf_life_days >= 0)));
ALTER TABLE public.ingredients ADD CONSTRAINT positive_purchase_size CHECK (((purchase_unit_size IS NULL) OR (purchase_unit_size > (0)::numeric)));
ALTER TABLE public.inventory_balances ADD CONSTRAINT non_negative_par_level CHECK ((par_level >= (0)::numeric));
ALTER TABLE public.inventory_balances ADD CONSTRAINT non_negative_reorder_point CHECK ((reorder_point >= (0)::numeric));
ALTER TABLE public.inventory_balances ADD CONSTRAINT non_negative_reserved CHECK ((reserved_quantity >= (0)::numeric));
ALTER TABLE public.location_opening_hours ADD CONSTRAINT location_opening_hours_day_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
ALTER TABLE public.location_opening_hours ADD CONSTRAINT location_opening_hours_time_required CHECK (((is_closed = true) OR ((opens_at IS NOT NULL) AND (closes_at IS NOT NULL) AND (opens_at <> closes_at))));
ALTER TABLE public.locations ADD CONSTRAINT beach_cart_requires_compound CHECK (((type <> 'beach_cart'::public.location_type) OR (compound_name IS NOT NULL)));
ALTER TABLE public.locations ADD CONSTRAINT locations_delivery_fee_non_negative CHECK ((delivery_fee >= (0)::numeric));
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT non_negative_points_balance CHECK ((points_balance >= 0));
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_price_non_negative CHECK ((unit_price_inc_vat_snapshot >= (0)::numeric));
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_qty_positive CHECK ((quantity_per_parent > 0));
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_serving_count_positive CHECK ((serving_count_snapshot > 0));
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_vat_valid CHECK (((vat_rate_snapshot >= (0)::numeric) AND (vat_rate_snapshot <= (1)::numeric)));
ALTER TABLE public.order_item_inventory_components ADD CONSTRAINT order_item_inventory_qty_positive CHECK ((quantity_per_order_item_unit > (0)::numeric));
ALTER TABLE public.order_item_inventory_components ADD CONSTRAINT order_item_inventory_source_valid CHECK ((source_type = ANY (ARRAY['base_recipe'::text, 'addon_recipe'::text])));
ALTER TABLE public.order_item_removed_ingredients ADD CONSTRAINT order_item_removed_ingredients_quantity_non_negative CHECK ((quantity_snapshot >= (0)::numeric));
ALTER TABLE public.order_items ADD CONSTRAINT non_negative_line_total CHECK ((line_total >= (0)::numeric));
ALTER TABLE public.order_items ADD CONSTRAINT non_negative_unit_price CHECK ((unit_price_inc_vat_snapshot >= (0)::numeric));
ALTER TABLE public.order_items ADD CONSTRAINT order_items_base_price_non_negative CHECK (((base_unit_price_inc_vat_snapshot IS NULL) OR (base_unit_price_inc_vat_snapshot >= (0)::numeric)));
ALTER TABLE public.order_items ADD CONSTRAINT order_items_customization_total_non_negative CHECK ((customization_total_inc_vat_snapshot >= (0)::numeric));
ALTER TABLE public.order_items ADD CONSTRAINT positive_order_quantity CHECK ((quantity > 0));
ALTER TABLE public.order_items ADD CONSTRAINT valid_vat_rate_snapshot CHECK (((vat_rate_snapshot >= (0)::numeric) AND (vat_rate_snapshot <= (1)::numeric)));
ALTER TABLE public.orders ADD CONSTRAINT non_negative_order_amounts CHECK (((subtotal_ex_vat >= (0)::numeric) AND (vat_amount >= (0)::numeric) AND (discount_amount >= (0)::numeric) AND (delivery_fee >= (0)::numeric) AND (total_amount >= (0)::numeric)));
ALTER TABLE public.orders ADD CONSTRAINT orders_asap_only CHECK ((requested_fulfillment_at IS NULL));
ALTER TABLE public.orders ADD CONSTRAINT orders_credit_applied_nonnegative_chk CHECK ((credit_applied >= (0)::numeric));
ALTER TABLE public.orders ADD CONSTRAINT orders_customer_phone_snapshot_egypt_mobile CHECK (((customer_phone_snapshot IS NULL) OR (customer_phone_snapshot ~ '^0[0-9]{10}$'::text)));
ALTER TABLE public.orders ADD CONSTRAINT valid_order_channel CHECK ((order_channel = ANY (ARRAY['app'::text, 'whatsapp'::text, 'walkup'::text, 'phone'::text])));
ALTER TABLE public.payments ADD CONSTRAINT positive_payment_amount CHECK ((amount >= (0)::numeric));
ALTER TABLE public.product_liquor_compatibility ADD CONSTRAINT non_negative_liquor_ml CHECK (((required_ml_per_serving IS NULL) OR (required_ml_per_serving >= (0)::numeric)));
ALTER TABLE public.product_tags ADD CONSTRAINT product_tags_color_hex_format CHECK ((color_hex ~ '^#[0-9A-Fa-f]{6}$'::text));
ALTER TABLE public.product_tags ADD CONSTRAINT product_tags_name_max_40 CHECK ((char_length(name) <= 40));
ALTER TABLE public.product_tags ADD CONSTRAINT product_tags_name_not_blank CHECK ((length(btrim(name)) > 0));
ALTER TABLE public.product_variants ADD CONSTRAINT non_negative_price CHECK ((price_ex_vat >= (0)::numeric));
ALTER TABLE public.product_variants ADD CONSTRAINT positive_serving_count CHECK ((serving_count > 0));
ALTER TABLE public.product_variants ADD CONSTRAINT valid_vat_rate CHECK (((vat_rate >= (0)::numeric) AND (vat_rate <= (1)::numeric)));
ALTER TABLE public.products ADD CONSTRAINT positive_prep_time CHECK ((prep_time_minutes >= 0));
ALTER TABLE public.products ADD CONSTRAINT products_short_description_max_40 CHECK (((short_description IS NULL) OR (char_length(short_description) <= 40)));
ALTER TABLE public.promotion_redemptions ADD CONSTRAINT non_negative_redemption_discount CHECK ((discount_amount >= (0)::numeric));
ALTER TABLE public.promotions ADD CONSTRAINT non_negative_discount_value CHECK ((discount_value >= (0)::numeric));
ALTER TABLE public.promotions ADD CONSTRAINT non_negative_min_order_value CHECK ((min_order_value >= (0)::numeric));
ALTER TABLE public.promotions ADD CONSTRAINT positive_usage_limit CHECK (((usage_limit IS NULL) OR (usage_limit > 0)));
ALTER TABLE public.purchase_order_items ADD CONSTRAINT non_negative_purchase_quantities CHECK (((ordered_quantity >= (0)::numeric) AND (received_quantity >= (0)::numeric) AND (unit_cost >= (0)::numeric)));
ALTER TABLE public.purchase_orders ADD CONSTRAINT non_negative_po_total CHECK ((total_cost >= (0)::numeric));
ALTER TABLE public.purchase_orders ADD CONSTRAINT valid_purchase_order_status CHECK ((status = ANY (ARRAY['draft'::text, 'ordered'::text, 'partially_received'::text, 'received'::text, 'cancelled'::text])));
ALTER TABLE public.recipe_items ADD CONSTRAINT positive_recipe_quantity CHECK ((quantity >= (0)::numeric));
ALTER TABLE public.recipes ADD CONSTRAINT positive_recipe_version CHECK ((version > 0));
ALTER TABLE public.recipes ADD CONSTRAINT positive_recipe_yield CHECK ((yield_servings > 0));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_singleton CHECK ((id = true));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_min_order_nonnegative_chk CHECK ((min_qualifying_order_value >= (0)::numeric));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_referee_discount_type_chk CHECK ((referee_discount_type = ANY (ARRAY['percentage'::text, 'fixed_amount'::text])));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_referee_discount_value_chk CHECK (((referee_discount_value >= (0)::numeric) AND ((referee_discount_type <> 'percentage'::text) OR (referee_discount_value <= (100)::numeric))));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_referee_max_discount_nonnegative_chk CHECK (((referee_max_discount_amount IS NULL) OR (referee_max_discount_amount >= (0)::numeric)));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_referrer_reward_nonnegative_chk CHECK ((referrer_reward_amount >= (0)::numeric));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_reward_cap_nonnegative_chk CHECK (((reward_cap_per_referrer IS NULL) OR (reward_cap_per_referrer >= 0)));
ALTER TABLE public.referral_settings ADD CONSTRAINT referral_settings_terms_length_chk CHECK (((terms IS NULL) OR (char_length(terms) <= 2000)));
ALTER TABLE public.referrals ADD CONSTRAINT referrals_no_self_referral CHECK ((referrer_customer_id <> referee_customer_id));
ALTER TABLE public.referrals ADD CONSTRAINT referrals_referee_discount_nonnegative_chk CHECK ((referee_discount_amount >= (0)::numeric));
ALTER TABLE public.referrals ADD CONSTRAINT referrals_referrer_reward_nonnegative_chk CHECK ((referrer_reward_amount >= (0)::numeric));
ALTER TABLE public.referrals ADD CONSTRAINT referrals_status_chk CHECK ((status = ANY (ARRAY['pending'::text, 'qualified'::text, 'rewarded'::text, 'void'::text])));
ALTER TABLE public.shop_settings ADD CONSTRAINT shop_settings_singleton CHECK ((id = true));
ALTER TABLE public.stock_movements ADD CONSTRAINT non_negative_unit_cost CHECK (((unit_cost IS NULL) OR (unit_cost >= (0)::numeric)));
ALTER TABLE public.stock_movements ADD CONSTRAINT non_zero_quantity_delta CHECK ((quantity_delta <> (0)::numeric));
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT non_negative_transfer_qty CHECK (((requested_qty >= (0)::numeric) AND (dispatched_qty >= (0)::numeric) AND (received_qty >= (0)::numeric)));
ALTER TABLE public.stock_transfers ADD CONSTRAINT different_transfer_locations CHECK ((from_location_id <> to_location_id));

-- ---------------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------------

ALTER TABLE public.app_events ADD CONSTRAINT app_events_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE public.cart_daily_closings ADD CONSTRAINT cart_daily_closings_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id);
ALTER TABLE public.cart_daily_closings ADD CONSTRAINT cart_daily_closings_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.cart_daily_openings ADD CONSTRAINT cart_daily_openings_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id);
ALTER TABLE public.cart_daily_openings ADD CONSTRAINT cart_daily_openings_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_addon_product_id_fkey FOREIGN KEY (addon_product_id) REFERENCES public.products(id);
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_addon_recipe_id_fkey FOREIGN KEY (addon_recipe_id) REFERENCES public.recipes(id);
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_addon_variant_id_fkey FOREIGN KEY (addon_variant_id) REFERENCES public.product_variants(id);
ALTER TABLE public.cart_item_additions ADD CONSTRAINT cart_item_additions_cart_item_id_fkey FOREIGN KEY (cart_item_id) REFERENCES public.cart_items(id) ON DELETE CASCADE;
ALTER TABLE public.cart_item_removed_ingredients ADD CONSTRAINT cart_item_removed_ingredients_cart_item_id_fkey FOREIGN KEY (cart_item_id) REFERENCES public.cart_items(id) ON DELETE CASCADE;
ALTER TABLE public.cart_item_removed_ingredients ADD CONSTRAINT cart_item_removed_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.cart_item_removed_ingredients ADD CONSTRAINT cart_item_removed_ingredients_recipe_item_id_fkey FOREIGN KEY (recipe_item_id) REFERENCES public.recipe_items(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id) ON DELETE CASCADE;
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id);
ALTER TABLE public.carts ADD CONSTRAINT carts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE public.customer_addresses ADD CONSTRAINT customer_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customer_credit_ledger ADD CONSTRAINT customer_credit_ledger_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customer_credit_ledger ADD CONSTRAINT customer_credit_ledger_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE public.customer_credit_ledger ADD CONSTRAINT customer_credit_ledger_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id);
ALTER TABLE public.customer_favorite_products ADD CONSTRAINT customer_favorite_products_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customer_favorite_products ADD CONSTRAINT customer_favorite_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.customer_notifications ADD CONSTRAINT customer_notifications_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customer_notifications ADD CONSTRAINT customer_notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.customer_payment_methods ADD CONSTRAINT customer_payment_methods_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customer_push_tokens ADD CONSTRAINT customer_push_tokens_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customers ADD CONSTRAINT customers_referred_by_customer_id_fkey FOREIGN KEY (referred_by_customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE public.employee_credentials ADD CONSTRAINT employee_credentials_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
ALTER TABLE public.employees ADD CONSTRAINT employees_default_location_id_fkey FOREIGN KEY (default_location_id) REFERENCES public.locations(id);
ALTER TABLE public.inventory_balances ADD CONSTRAINT inventory_balances_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.inventory_balances ADD CONSTRAINT inventory_balances_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.location_opening_hours ADD CONSTRAINT location_opening_hours_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE;
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT loyalty_accounts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.loyalty_transactions ADD CONSTRAINT loyalty_transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.loyalty_transactions ADD CONSTRAINT loyalty_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE public.order_inventory_consumptions ADD CONSTRAINT order_inventory_consumptions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_addon_product_id_fkey FOREIGN KEY (addon_product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_addon_recipe_id_fkey FOREIGN KEY (addon_recipe_id) REFERENCES public.recipes(id) ON DELETE SET NULL;
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_addon_variant_id_fkey FOREIGN KEY (addon_variant_id) REFERENCES public.product_variants(id) ON DELETE SET NULL;
ALTER TABLE public.order_item_additions ADD CONSTRAINT order_item_additions_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) ON DELETE CASCADE;
ALTER TABLE public.order_item_inventory_components ADD CONSTRAINT order_item_inventory_components_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.order_item_inventory_components ADD CONSTRAINT order_item_inventory_components_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) ON DELETE CASCADE;
ALTER TABLE public.order_item_removed_ingredients ADD CONSTRAINT order_item_removed_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id) ON DELETE SET NULL;
ALTER TABLE public.order_item_removed_ingredients ADD CONSTRAINT order_item_removed_ingredients_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) ON DELETE CASCADE;
ALTER TABLE public.order_item_removed_ingredients ADD CONSTRAINT order_item_removed_ingredients_recipe_item_id_fkey FOREIGN KEY (recipe_item_id) REFERENCES public.recipe_items(id) ON DELETE SET NULL;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id);
ALTER TABLE public.order_prep_tasks ADD CONSTRAINT order_prep_tasks_assigned_employee_id_fkey FOREIGN KEY (assigned_employee_id) REFERENCES public.employees(id);
ALTER TABLE public.order_prep_tasks ADD CONSTRAINT order_prep_tasks_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) ON DELETE CASCADE;
ALTER TABLE public.order_prep_tasks ADD CONSTRAINT order_prep_tasks_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.prep_stations(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_customer_address_id_fkey FOREIGN KEY (customer_address_id) REFERENCES public.customer_addresses(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id) ON DELETE SET NULL;
ALTER TABLE public.payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.prep_stations ADD CONSTRAINT prep_stations_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.product_liquor_compatibility ADD CONSTRAINT product_liquor_compatibility_liquor_type_id_fkey FOREIGN KEY (liquor_type_id) REFERENCES public.liquor_types(id) ON DELETE CASCADE;
ALTER TABLE public.product_liquor_compatibility ADD CONSTRAINT product_liquor_compatibility_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id);
ALTER TABLE public.promotion_redemptions ADD CONSTRAINT promotion_redemptions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id);
ALTER TABLE public.promotion_redemptions ADD CONSTRAINT promotion_redemptions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE public.promotion_redemptions ADD CONSTRAINT promotion_redemptions_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id);
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);
ALTER TABLE public.recipe_items ADD CONSTRAINT recipe_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.recipe_items ADD CONSTRAINT recipe_items_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE;
ALTER TABLE public.recipes ADD CONSTRAINT recipes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.referrals ADD CONSTRAINT referrals_qualifying_order_id_fkey FOREIGN KEY (qualifying_order_id) REFERENCES public.orders(id);
ALTER TABLE public.referrals ADD CONSTRAINT referrals_referee_customer_id_fkey FOREIGN KEY (referee_customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.referrals ADD CONSTRAINT referrals_referrer_customer_id_fkey FOREIGN KEY (referrer_customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_related_order_fk FOREIGN KEY (related_order_id) REFERENCES public.orders(id) ON DELETE SET NULL;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_related_transfer_fk FOREIGN KEY (related_transfer_id) REFERENCES public.stock_transfers(id) ON DELETE SET NULL;
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.stock_transfers(id) ON DELETE CASCADE;
ALTER TABLE public.stock_transfer_movement_events ADD CONSTRAINT stock_transfer_movement_events_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.stock_transfers(id) ON DELETE CASCADE;
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_dispatched_by_fkey FOREIGN KEY (dispatched_by) REFERENCES public.employees(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES public.locations(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.employees(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.employees(id);
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES public.locations(id);

-- ---------------------------------------------------------------------------
-- Demand forecasting module (server/forecast/), migration 20260807171440.
-- Appended as a block rather than sorted inline; the next full run of
-- ../tools/dump_schema.sql will re-sort these into place.
-- ---------------------------------------------------------------------------

ALTER TABLE public.forecast_accuracy_cart ADD CONSTRAINT forecast_accuracy_cart_pkey PRIMARY KEY (location_id, business_date, horizon_days);
ALTER TABLE public.forecast_accuracy_product ADD CONSTRAINT forecast_accuracy_product_pkey PRIMARY KEY (location_id, business_date, product_id, horizon_days);
ALTER TABLE public.forecast_campaign_effects ADD CONSTRAINT forecast_campaign_effects_pkey PRIMARY KEY (campaign_type, discount_bucket);
ALTER TABLE public.forecast_campaign_locations ADD CONSTRAINT forecast_campaign_locations_pkey PRIMARY KEY (campaign_id, location_id);
ALTER TABLE public.forecast_campaign_observations ADD CONSTRAINT forecast_campaign_observations_pkey PRIMARY KEY (campaign_id, location_id, business_date);
ALTER TABLE public.forecast_campaign_products ADD CONSTRAINT forecast_campaign_products_pkey PRIMARY KEY (campaign_id, product_id);
ALTER TABLE public.forecast_campaigns ADD CONSTRAINT forecast_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.forecast_cart_assumptions ADD CONSTRAINT forecast_cart_assumptions_pkey PRIMARY KEY (location_id, day_of_week);
ALTER TABLE public.forecast_cart_state ADD CONSTRAINT forecast_cart_state_pkey PRIMARY KEY (location_id);
ALTER TABLE public.forecast_daily_cart ADD CONSTRAINT forecast_daily_cart_pkey PRIMARY KEY (location_id, business_date);
ALTER TABLE public.forecast_daily_product ADD CONSTRAINT forecast_daily_product_pkey PRIMARY KEY (location_id, business_date, product_id);
ALTER TABLE public.forecast_demand_daily_cart ADD CONSTRAINT forecast_demand_daily_cart_pkey PRIMARY KEY (location_id, business_date);
ALTER TABLE public.forecast_demand_daily_product ADD CONSTRAINT forecast_demand_daily_product_pkey PRIMARY KEY (location_id, business_date, product_id);
ALTER TABLE public.forecast_network_state ADD CONSTRAINT forecast_network_state_pkey PRIMARY KEY (id);
ALTER TABLE public.forecast_product_state ADD CONSTRAINT forecast_product_state_pkey PRIMARY KEY (location_id, product_id);
ALTER TABLE public.forecast_runs ADD CONSTRAINT forecast_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.forecast_campaign_effects ADD CONSTRAINT forecast_campaign_effects_pull_forward_range CHECK (((pull_forward_ratio >= (0)::numeric) AND (pull_forward_ratio <= (1)::numeric)));
ALTER TABLE public.forecast_campaigns ADD CONSTRAINT forecast_campaigns_dates_ordered CHECK ((ends_on >= starts_on));
ALTER TABLE public.forecast_campaigns ADD CONSTRAINT forecast_campaigns_scope_valid CHECK ((scope = ANY (ARRAY['network'::text, 'cart'::text, 'product'::text])));
ALTER TABLE public.forecast_campaigns ADD CONSTRAINT forecast_campaigns_uplift_sane CHECK ((expected_uplift_pct > ('-100'::integer)::numeric));
ALTER TABLE public.forecast_cart_assumptions ADD CONSTRAINT forecast_cart_assumptions_dow_range CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
ALTER TABLE public.forecast_cart_assumptions ADD CONSTRAINT forecast_cart_assumptions_strength_positive CHECK ((prior_strength_days > 0));
ALTER TABLE public.forecast_cart_assumptions ADD CONSTRAINT forecast_cart_assumptions_units_non_negative CHECK (((expected_units IS NULL) OR (expected_units >= (0)::numeric)));
ALTER TABLE public.forecast_cart_state ADD CONSTRAINT forecast_cart_state_dow_count_len CHECK ((array_length(dow_obs_count, 1) = 7));
ALTER TABLE public.forecast_cart_state ADD CONSTRAINT forecast_cart_state_dow_index_len CHECK ((array_length(dow_index, 1) = 7));
ALTER TABLE public.forecast_daily_cart ADD CONSTRAINT forecast_daily_cart_confidence_valid CHECK ((confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])));
ALTER TABLE public.forecast_daily_cart ADD CONSTRAINT forecast_daily_cart_quantiles_ordered CHECK ((p90 >= p50));
ALTER TABLE public.forecast_daily_product ADD CONSTRAINT forecast_daily_product_confidence_valid CHECK ((confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])));
ALTER TABLE public.forecast_daily_product ADD CONSTRAINT forecast_daily_product_quantiles_ordered CHECK ((p90 >= p50));
ALTER TABLE public.forecast_demand_daily_cart ADD CONSTRAINT forecast_demand_daily_cart_orders_non_negative CHECK ((orders >= 0));
ALTER TABLE public.forecast_demand_daily_cart ADD CONSTRAINT forecast_demand_daily_cart_units_non_negative CHECK ((units >= 0));
ALTER TABLE public.forecast_demand_daily_cart ADD CONSTRAINT forecast_demand_daily_cart_uplift_positive CHECK ((applied_uplift > (0)::numeric));
ALTER TABLE public.forecast_demand_daily_product ADD CONSTRAINT forecast_demand_daily_product_units_non_negative CHECK ((units >= 0));
ALTER TABLE public.forecast_demand_daily_product ADD CONSTRAINT forecast_demand_daily_product_uplift_positive CHECK ((applied_uplift > (0)::numeric));
ALTER TABLE public.forecast_network_state ADD CONSTRAINT forecast_network_state_dow_index_len CHECK ((array_length(dow_index, 1) = 7));
ALTER TABLE public.forecast_network_state ADD CONSTRAINT forecast_network_state_singleton CHECK ((id = true));
ALTER TABLE public.forecast_product_state ADD CONSTRAINT forecast_product_state_alpha_non_negative CHECK ((alpha >= (0)::numeric));
ALTER TABLE public.forecast_runs ADD CONSTRAINT forecast_runs_status_valid CHECK ((status = ANY (ARRAY['running'::text, 'ok'::text, 'failed'::text])));
ALTER TABLE public.forecast_runs ADD CONSTRAINT forecast_runs_trigger_valid CHECK ((trigger = ANY (ARRAY['schedule'::text, 'manual'::text, 'rebuild'::text, 'backtest'::text])));
ALTER TABLE public.forecast_accuracy_cart ADD CONSTRAINT forecast_accuracy_cart_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_accuracy_product ADD CONSTRAINT forecast_accuracy_product_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_accuracy_product ADD CONSTRAINT forecast_accuracy_product_product_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaign_locations ADD CONSTRAINT forecast_campaign_locations_campaign_fkey FOREIGN KEY (campaign_id) REFERENCES forecast_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaign_locations ADD CONSTRAINT forecast_campaign_locations_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaign_observations ADD CONSTRAINT forecast_campaign_observations_campaign_fkey FOREIGN KEY (campaign_id) REFERENCES forecast_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaign_observations ADD CONSTRAINT forecast_campaign_observations_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaign_products ADD CONSTRAINT forecast_campaign_products_campaign_fkey FOREIGN KEY (campaign_id) REFERENCES forecast_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaign_products ADD CONSTRAINT forecast_campaign_products_product_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_campaigns ADD CONSTRAINT forecast_campaigns_promotion_fkey FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE SET NULL;
ALTER TABLE public.forecast_cart_assumptions ADD CONSTRAINT forecast_cart_assumptions_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_cart_assumptions ADD CONSTRAINT forecast_cart_assumptions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.forecast_cart_state ADD CONSTRAINT forecast_cart_state_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_daily_cart ADD CONSTRAINT forecast_daily_cart_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_daily_product ADD CONSTRAINT forecast_daily_product_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_daily_product ADD CONSTRAINT forecast_daily_product_product_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_demand_daily_cart ADD CONSTRAINT forecast_demand_daily_cart_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_demand_daily_product ADD CONSTRAINT forecast_demand_daily_product_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_demand_daily_product ADD CONSTRAINT forecast_demand_daily_product_product_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_product_state ADD CONSTRAINT forecast_product_state_location_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE public.forecast_product_state ADD CONSTRAINT forecast_product_state_product_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
