import { useState } from 'react';
import { api } from '../api/client.js';
import { baseUnits } from '../config/constants.js';
import { Loading, Message, Section, SimpleTable } from '../components/ui.jsx';
import { useLoad } from '../hooks/useLoad.js';
import { splitTags, toBool } from '../utils/format.js';

export default function Ingredients() {
  const { data, loading, error, reload } = useLoad(() => api('/api/ingredients'));
  const blank = { name:'', category:'', base_unit:'ml', purchase_unit_name:'', purchase_unit_size:'', purchase_unit_cost:'', cost_per_base_unit:'', is_perishable:false, shelf_life_days:'', allergen_flags:'', is_customer_supplied:false, is_active:true };
  const [form, setForm] = useState(blank);
  const [editing, setEditing] = useState(null);
  const [msg, setMsg] = useState('');
  async function save(e) { e.preventDefault(); setMsg(''); const payload = { ...form, allergen_flags: splitTags(form.allergen_flags), is_perishable: toBool(form.is_perishable), is_customer_supplied: toBool(form.is_customer_supplied), is_active: toBool(form.is_active) }; if (editing) await api(`/api/ingredients/${editing}`, { method:'PATCH', body: JSON.stringify(payload) }); else await api('/api/ingredients', { method:'POST', body: JSON.stringify(payload) }); setForm(blank); setEditing(null); setMsg('Saved.'); reload(); }
  function edit(row) { setEditing(row.id); setForm({ ...blank, ...row, allergen_flags: (row.allergen_flags || []).join(', ') }); window.scrollTo({top:0, behavior:'smooth'}); }
  if (loading || error) return <Loading error={error} />;
  return <div className="grid"><Section title={editing ? 'Edit Ingredient' : 'Add Ingredient'} action={editing && <button onClick={() => { setEditing(null); setForm(blank); }}>Cancel edit</button>}><form className="miniForm formGrid" onSubmit={save}><input required placeholder="Name" value={form.name} onChange={e => setForm({...form, name:e.target.value})}/><input placeholder="Category" value={form.category || ''} onChange={e => setForm({...form, category:e.target.value})}/><select value={form.base_unit} onChange={e => setForm({...form, base_unit:e.target.value})}>{baseUnits.map(u => <option key={u}>{u}</option>)}</select><input placeholder="Purchase unit name e.g. 1L bottle" value={form.purchase_unit_name || ''} onChange={e => setForm({...form, purchase_unit_name:e.target.value})}/><input type="number" step="0.001" placeholder="Purchase unit size" value={form.purchase_unit_size || ''} onChange={e => setForm({...form, purchase_unit_size:e.target.value})}/><input type="number" step="0.01" placeholder="Purchase unit cost" value={form.purchase_unit_cost || ''} onChange={e => setForm({...form, purchase_unit_cost:e.target.value})}/><input type="number" step="0.000001" placeholder="Cost per base unit" value={form.cost_per_base_unit || ''} onChange={e => setForm({...form, cost_per_base_unit:e.target.value})}/><input type="number" placeholder="Shelf life days" value={form.shelf_life_days || ''} onChange={e => setForm({...form, shelf_life_days:e.target.value})}/><input placeholder="Allergens, comma separated" value={form.allergen_flags || ''} onChange={e => setForm({...form, allergen_flags:e.target.value})}/><label><input type="checkbox" checked={toBool(form.is_perishable)} onChange={e => setForm({...form, is_perishable:e.target.checked})}/> Perishable</label><label><input type="checkbox" checked={toBool(form.is_customer_supplied)} onChange={e => setForm({...form, is_customer_supplied:e.target.checked})}/> Customer supplied</label><label><input type="checkbox" checked={toBool(form.is_active)} onChange={e => setForm({...form, is_active:e.target.checked})}/> Active</label><button className="primary">{editing ? 'Save Changes' : 'Add Ingredient'}</button></form><Message text={msg}/></Section>
    <Section title="Ingredients"><SimpleTable rows={data} columns={['name','category','base_unit','purchase_unit_cost','cost_per_base_unit','is_perishable','is_customer_supplied','is_active']} actions={(r) => <button onClick={() => edit(r)}>Edit</button>} /></Section></div>;
}